### ISSUE TITLE
q is not defined

### ISSUE THREAD

**Issue by ghost** [rafaelkaufmann/q-orm#4]
Hi,
thanks for this awesome plugin.
I found the following issues: 
1. npm install version is different then github version- no qFind method for example.
2. in qFind method (line 119) please change from q(undefined) to Q
 return q.npost

cheers.

**Comment by rafaelkaufmann** [comment]
Hi @liorru , thanks for the feedbacks! I have just published 0.0.2 to npm. About your second issue, can you fix this and send a pull request?

Cheers,

**Comment by ghost** [comment]
Hi,
I see some one already did it :)

**Comment by rafaelkaufmann** [comment]
Yes, I just merged :)

**Comment by lightrabbit** [comment]
Hi @rafaelkaufmann , I install `q-orm` by using `npm install q-orm`. But I still get the package with this issue. Can you publish a new version of this package to npm?

cheers.

**Comment by rafaelkaufmann** [comment]
Done! Thanks for the heads up. Let me know if 0.0.3 solves it for you.

2015-07-21 6:59 GMT-03:00 lightrabbit notifications@github.com:

> Hi @rafaelkaufmann https://github.com/rafaelkaufmann , I install q-orm
> by using npm install q-orm. But I still get the package with this issue.
> Can you publish a new version of this package to npm?
> 
> cheers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rafaelkaufmann/q-orm/issues/4#issuecomment-123246503.

## 

_Rafael Kaufmann_

Praia de Botafogo 501 . Torre Pão de Açúcar . Sala 135/136
22250-040 . Rio de Janeiro . RJ

_c_ 55 21 98220.7030

rafael.kaufmann@resolveai.com.br
www.resolveai.com.br

Esta mensagem e seus anexos podem conter informações privilegiadas e/ou de
caráter confidencial, não podendo ser retransmitidos sem autorização do
remetente.
Se você recebeu essa mensagem por engano, por favor, responda este e-mail,
excluindo-o em seguida.

This e-mail and attachments may contain confidential data or information
and may
be legally privileged, therefore cannot be read, copied, printed or
forwarded or disclosed
to any person without the sender's previous authorization. If you have
received it in error,
please reply to this e-mail notifying the sender and delete it immediately
afterwards.

**Comment by lightrabbit** [comment]
Thanks! 0.0.3 solves it.
